#! /usr/bin/env python3

import os
import sqlite3


# Create DB file and set up connection
if os.path.exists('app.db'):
	os.remove('app.db')

con = sqlite3.connect('app.db')
cur = con.cursor()
cur.execute('''PRAGMA foreign_keys = 1''')

# Create Tables
cur.execute('''CREATE TABLE locations(
	id integer PRIMARY KEY, 
	city text NOT NULL, 
	state text, 
	country text NOT NULL)''')

cur.execute('''CREATE TABLE reviews(
	id integer PRIMARY KEY,
	locationId integer,
	name text NOT NULL,
	review text NOT NULL,
	FOREIGN KEY(locationId) REFERENCES locations(id))''')

# Insert Locations
locs = [(1, 'Seattle', 'WA', 'United States'),
		(2, 'Portland', 'OR', 'United States'),
		(3, 'Grays Point', 'NSW', 'Australia')]

cur.executemany("INSERT INTO locations (id, city, state, country) VALUES (?, ?, ?, ?)", locs)

reviews = [(1, 'Andrew Anderson', 'This place sux!'),
			(1, 'Bob Bobson', 'I love this place'),
			(2, 'Cindy Cinderson', 'The restaurants here are great'),
			(2, 'Danielle Danielson', 'I had a terrible experience at Jack in the Box'),
			(3, 'Erik Erikson', 'Too hot'),
			(3, 'Frances Francis', 'Too many birds')]

cur.executemany("INSERT INTO reviews (locationId, name, review) VALUES (?, ?, ?)", reviews)

con.commit()
con.close()

	 
