#! /usr/bin/env python3

import os
import sqlite3


# Create DB file and set up connection
if os.path.exists('app.db'):
	os.remove('app.db')
con = sqlite3.connect('app.db')
cur = con.cursor()
cur.execute('''PRAGMA foreign_keys = 1''')
cur.execute('''PRAGMA case_sensitive_like=OFF''')

# Create Tables
cur.execute('''CREATE TABLE locations(
	id integer PRIMARY KEY, 
	city text NOT NULL, 
	state text, 
	country text NOT NULL,
	searchTerm text NOT NULL)''')
cur.execute('''CREATE TABLE reviews(
	id integer PRIMARY KEY,
	locationId integer,
	name text NOT NULL,
	review text NOT NULL,
	FOREIGN KEY(locationId) REFERENCES locations(id))''')
cur.execute('''CREATE TABLE stateAbbrs(
	id integer PRIMARY KEY,
	nameLong text NOT NULL,
	nameAbbr text NOT NULL,
	country text NOT NULL)''')	

# Insert Locations
locs = [(1, 'Redmond', 'WA', 'United States', 'Redmond, Washington'),
		(2, 'Corvallis', 'OR', 'United States', 'Corvallis, Oregon'),
		(3, 'Grays Point', 'NSW', 'Australia', 'Grays Point, New South Wales'),
		(4, 'Zzyzx', 'CA', 'United States', 'Zzyzx, California')]
cur.executemany("INSERT INTO locations (id, city, state, country, searchTerm) VALUES (?, ?, ?, ?, ?)", \
	locs)

# Insert Reviews
reviews = [(1, 'Andrew Anderson', 'This place sux!'),
			(1, 'Bob Bobson', 'I love this place'),
			(2, 'Cindy Cinderson', 'The restaurants here are great'),
			(2, 'Danielle Danielson', 'I had a terrible experience at Jack in the Box'),
			(3, 'Erik Erikson', 'Too hot'),
			(3, 'Frances Francis', 'Too many birds'),
			(4, 'George George', 'Great scenery'),
			(4, 'Hanna Hansen', 'Not much to do. I didn\'t enjoy it')
			]
cur.executemany("INSERT INTO reviews (locationId, name, review) VALUES (?, ?, ?)", \
	reviews)

# Insert State Abbreviations
abbrs = [('WA', 'Washington', 'United States'),
		('OR', 'Oregon', 'United States'),
		('CA', 'California', 'United States'),
		('NSW', 'New South Wales', 'Australia')]
cur.executemany("INSERT INTO stateAbbrs (nameAbbr, nameLong, country) VALUES (?, ?, ?)", \
	abbrs)

con.commit()
con.close()
